### PR TITLE
Guards and null checks against unsaved fragment transactions on configuration change

### LINKED ISSUE #1555: Fragment MainFragment{fb222c4} is not currently in the FragmentManager on install
```
12-28 14:22:12.244 com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager.debug, PID: 17898
    java.lang.IllegalStateException: Fragment MainFragment{fb222c4} is not currently in the FragmentManager
        at android.support.v4.app.FragmentManagerImpl.putFragment(FragmentManager.java:923)
        at com.amaze.filemanager.fragments.TabFragment.onSaveInstanceState(TabFragment.java:269)
        at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2626)
        at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:2910)
        at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2971)
        at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:134)
        at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:591)
        at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:510)
        at com.amaze.filemanager.activities.MainActivity.onSaveInstanceState(MainActivity.java:1090)
        at android.app.Activity.performSaveInstanceState(Activity.java:1302)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1312)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4109)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3511)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3571)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

### PR DESCRIPTION
**Pull request by TranceLove**
#### Issue tracker   
Fixes #1555

#### Automatic tests
- [x] Added test cases
  
#### Manual tests
- [ ] Done  
  
#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by VishnuSanal** [comment]
Build test apk

File: app/src/androidTest/java/com/amaze/filemanager/ui/fragments/TabFragmentTest.kt [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+     * by rotate the screen while swiping between the tabs.
+     */
+    @Test
+    fun testFragmentStateSavingDuringConfigChange() {
+        // First perform the swipe action
+        onView(withId(R.id.pager)).perform(swipeLeft())
+
+        // Force a configuration change by rotating the screen
+        activityRule.activity.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE
+        Thread.sleep(1000) // Give time for the rotation to complete
```
Comment (EmmanuelMess) [inline app/src/androidTest/java/com/amaze/filemanager/ui/fragments/TabFragmentTest.kt:123]: Is using a constant time correct here? Doesn't it depend on the speed of the device whether it crashes or not?

**Comment by EmmanuelMess** [comment]
Got this when rotating after exiting the app for a bit:
```
2025-04-12 19:10:00.930 20736-20736 AndroidRuntime          com.amaze.filemanager.debug          E  FATAL EXCEPTION: main
                                                                                                    Process: com.amaze.filemanager.debug, PID: 20736
                                                                                                    java.lang.RuntimeException: Unable to create service leakcanary.internal.HeapAnalyzerService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{6ce9d89 20736:com.amaze.filemanager.debug/u0a400} targetSDK=34
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4787)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2368)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:242)
                                                                                                    	at android.os.Looper.loop(Looper.java:362)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8393)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
                                                                                                    Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{6ce9d89 20736:com.amaze.filemanager.debug/u0a400} targetSDK=34
                                                                                                    	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
                                                                                                    	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
                                                                                                    	at android.os.Parcel.readParcelableInternal(Parcel.java:4892)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:4874)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3074)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3063)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3046)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2988)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7154)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:85)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy4.setServiceForeground(Unknown Source)
                                                                                                    	at android.app.Service.startForeground(Service.java:775)
                                                                                                    	at leakcanary.internal.ForegroundService.showForegroundNotification(ForegroundService.kt:51)
                                                                                                    	at leakcanary.internal.ForegroundService.onCreate(ForegroundService.kt:33)
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4774)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2368) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:242) 
                                                                                                    	at android.os.Looper.loop(Looper.java:362) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8393) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992) 
2025-04-12 19:10:00.937 20736-20736 ACRA                    com.amaze.filemanager.debug          E  ACRA caught a RuntimeException for com.amaze.filemanager.debug
                                                                                                    java.lang.RuntimeException: Unable to create service leakcanary.internal.HeapAnalyzerService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{6ce9d89 20736:com.amaze.filemanager.debug/u0a400} targetSDK=34
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4787)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2368)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:242)
                                                                                                    	at android.os.Looper.loop(Looper.java:362)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8393)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
                                                                                                    Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{6ce9d89 20736:com.amaze.filemanager.debug/u0a400} targetSDK=34
                                                                                                    	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
                                                                                                    	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
                                                                                                    	at android.os.Parcel.readParcelableInternal(Parcel.java:4892)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:4874)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3074)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3063)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3046)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2988)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7154)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:85)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy4.setServiceForeground(Unknown Source)
                                                                                                    	at android.app.Service.startForeground(Service.java:775)
                                                                                                    	at leakcanary.internal.ForegroundService.showForegroundNotification(ForegroundService.kt:51)
                                                                                                    	at leakcanary.internal.ForegroundService.onCreate(ForegroundService.kt:33)
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4774)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2368) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:242) 
                                                                                                    	at android.os.Looper.loop(Looper.java:362) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8393) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992) 
```

But I think it might not be related.

**Comment by EmmanuelMess** [comment]
I cannot replicate the original bug in my Moto G73, app might be going too smoothly. Will try to replicate with just the tests.

**Comment by EmmanuelMess** [comment]
Okay, executing the emulator tests, I get the notifications permission request and the storage permissions popup. And the tests fail with:
```
androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1841)
at androidx.test.espresso.base.EspressoExceptionHandler.handleSafely(EspressoExceptionHandler.java:34)
at androidx.test.espresso.base.EspressoExceptionHandler.handleSafely(EspressoExceptionHandler.java:26)
at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:158)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:120)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:385)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:212)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:140)
at com.amaze.filemanager.ui.fragments.TabFragmentTest.testFragmentStateSavingDuringConfigChange(TabFragmentTest.kt:43)
```

Emulator: Pixel 9 API 34

File: app/src/main/java/com/amaze/filemanager/ui/fragments/TabFragment.java [hunk 2]
```diff
@@ -83,7 +84,7 @@ public class TabFragment extends Fragment {
   private boolean savePaths;
   private FragmentManager fragmentManager;
 
-  private final List<Fragment> fragments = new ArrayList<>();
+  final List<Fragment> fragments = new ArrayList<>();
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/ui/fragments/TabFragment.java]: This should probably be public only for tests. Add `@VisibleForTesting`

**Comment by EmmanuelMess** [comment]
For the robolectric tests, they pass both before and after the changes, which suggests it doesn't add as much new info.

**Comment by TranceLove** [comment]
> For the robolectric tests, they pass both before and after the changes, which suggests it doesn't add as much new info.

Indeed, as desktop JVM generally runs faster than Dalvik. Robolectric tests are just for keeping tests at par with Espresso ones.

**Comment by TranceLove** [comment]
> Okay, executing the emulator tests, I get the notifications permission request and the storage permissions popup. And the tests fail with:
> 
> ```
> androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
> at dalvik.system.VMStack.getThreadStackTrace(Native Method)
> at java.lang.Thread.getStackTrace(Thread.java:1841)
> at androidx.test.espresso.base.EspressoExceptionHandler.handleSafely(EspressoExceptionHandler.java:34)
> at androidx.test.espresso.base.EspressoExceptionHandler.handleSafely(EspressoExceptionHandler.java:26)
> at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:158)
> at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:120)
> at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:385)
> at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:212)
> at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:140)
> at com.amaze.filemanager.ui.fragments.TabFragmentTest.testFragmentStateSavingDuringConfigChange(TabFragmentTest.kt:43)
> ```
> 
> Emulator: Pixel 9 API 34

The nearest thing I can find: https://stackoverflow.com/questions/75814428/accessing-storage-from-orchestrated-espresso-test

Seems Espresso itself isn't going to do anything about this... yet.

**Comment by EmmanuelMess** [comment]
@TranceLove I've added a test and a few fixes, I would approve merging as is, closing the old issue and waiting for new reports.

**Review by EmmanuelMess — DISMISSED** [review]

**Review by VishnuSanal — APPROVED** [review]

**Review by EmmanuelMess — APPROVED** [review]
