### PR TITLE
Null safety for EditableFileAbstraction.hybridFileParcelable

### LINKED ISSUE #1184: Crash on text file opened
Opened mail from K-9 mail and it crashed:

```gradle
com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager, PID: 17321
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amaze.filemanager.filesystem.HybridFileParcelable.getPath()' on a null object reference
        at com.amaze.filemanager.activities.TextEditorActivity.lambda$load$4$TextEditorActivity(TextEditorActivity.java:296)
        at com.amaze.filemanager.activities.TextEditorActivity$$Lambda$3.onAsyncTaskFinished(Unknown Source)
        at com.amaze.filemanager.asynchronous.asynctasks.ReadFileTask.onPostExecute(ReadFileTask.java:125)
        at com.amaze.filemanager.asynchronous.asynctasks.ReadFileTask.onPostExecute(ReadFileTask.java:27)
        at android.os.AsyncTask.finish(AsyncTask.java:651)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
```

### PR DESCRIPTION
**Pull request by TranceLove**
Fixes #1184, when `content://` URI is passed into TextEditorActivity. Unit test included.

A note was also added to `AppConfig` indicating the requirement of running one test case at a time because of the background thread would be killed after a test case was finished running, which would not be fixed by this PR.

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/activities/TextEditorActivity.java [hunk 1]
```diff
@@ -293,7 +295,7 @@ private void load() {
                     try {
                         mInput.setText(data.fileContents);
 
-                        if (mFile.hybridFileParcelable.getPath().contains(getExternalCacheDir().getPath())
+                        if (mFile.hybridFileParcelable != null && mFile.hybridFileParcelable.getPath().contains(getExternalCacheDir().getPath())
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/activities/TextEditorActivity.java]: Sorry for the late respose.
Remember that `getExternalCacheDir()`
>May return null if shared storage is not currently available.

--[Android Deveplopers - getExternalCacheDir()](https://developer.android.com/reference/android/content/Context.html#getExternalCacheDir())
