### PR TITLE
Catch ActivityNotFoundException and launch web browser for app

### LINKED ISSUE #1139: Crashes if Play store not installed
App Manager -> [more] popup -> Play store
It crashes by ActivityNotFoundException

### PR DESCRIPTION
**Pull request by TranceLove**
Fixes #1139, app package's webpage on Google Play Store (if any) will be opened if user device does not have Google Play Store installed, which should be sufficient as almost all Android devices should have webview implementations.

Additionally
 * remove deprecated MaterialDialog.Builder.callback() to .onNegative() and .onPositive()
 * change HybridFileParcelable.getParent() to HybridFileParcelable.getParent(Context).
 * change hard-coded SDK version 21 to Build.VERSION_CODES.LOLLIPOP

Tested with Nougat emulator (no Google Play Services installed).

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
Can't test right now, but shouldn't open in Play Store be removed if it is not installed?

**Comment by TranceLove** [comment]
> Can't test right now, but shouldn't open in Play Store be removed if it is not installed?

It's indeed one of the alternatives... see 2bacd0a, but I'm open to both options.

File: app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java [hunk 1]
```diff
@@ -249,9 +242,23 @@ public void onPositive(MaterialDialog materialDialog) {
...
             popupMenu.show();
         });
 
     }
 
+    private final boolean isGooglePlayStoreAvailable() {
+        PackageManager pm = context.getPackageManager();
+        try {
+            pm.getPackageInfo(COM_ANDROID_VENDING, PackageManager.GET_ACTIVITIES);
+            return true;
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java]: When I test on emulator, the app crashes as before. I think the package is present but not the activity. Changing these lines to:
```java
    PackageInfo packageInfo = pm.getPackageInfo(COM_ANDROID_VENDING, PackageManager.GET_ACTIVITIES);
    return packageInfo.activities != null;
```
Seems to fix it.

File: app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java [hunk 2]
```diff
@@ -249,9 +242,23 @@ public void onPositive(MaterialDialog materialDialog) {
...
+        } catch (PackageManager.NameNotFoundException ifNotInstalled) {
+            ifNotInstalled.printStackTrace();
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java]: I think this just clutters the logcat, when printed it doesn't help, hence we shouldn't print it.

File: app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java (hunk 1 above)
Comment (TranceLove) [reply app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java]: Being a cautious one I'd check both.

File: app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java [hunk 3]
```diff
@@ -253,10 +254,9 @@ private void showPopup(View v, final AppDataParcelable rowItem){
     private final boolean isGooglePlayStoreAvailable() {
         PackageManager pm = context.getPackageManager();
         try {
-            pm.getPackageInfo(COM_ANDROID_VENDING, PackageManager.GET_ACTIVITIES);
-            return true;
+            PackageInfo appInfo = pm.getPackageInfo(COM_ANDROID_VENDING, PackageManager.GET_ACTIVITIES);
+            return appInfo != null || appInfo.activities != null;
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java]: Or? If `appInfo` is null `appInfo.activities` will NPE.

Comment (TranceLove) [reply app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java]: Oops.

**Comment by VishalNehra** [comment]
I think opening in browser is a good option in case play store is not installed.
A fix would be to not show this option in case the application is not signed with a playstore key (example system apps or debug/third party apps). However it doesn't concern this PR.

**Comment by EmmanuelMess** [comment]
> I think opening in browser is a good option in case play store is not installed.
> A fix would be to not show this option in case the application is not signed with a playstore key (example system apps or debug/third party apps). However it doesn't concern this PR.

This should go to an issue.

**Comment by VishalNehra** [comment]
Yes, but don't hide the option in this PR, open it with browser.
