### PR TITLE
fix: selected item is unselected after clicking 'Select All' when there is only one item in the directory

### LINKED ISSUE #4327: Selected item is unselected after clicking 'Select All' when there is only one item in the directory
**Describe the bug**
When there is only one item in the Trash Bin, the selected item is cancelled after clicking 'Select All'

**To Reproduce**
1. Click on 'Hamburger' menu
2. Click on 'Trash Bin'
3. Long press to select an item
4. Click on 'v' icon
5. Click on 'Select All'

**Expected behavior**
The selected item should remain selected after clicking ‘Select All’, even if it is the only item in the Trash Bin.

**Screen Recording**

https://github.com/user-attachments/assets/93d32212-ed70-4ef6-bb8e-f6899093ab4f

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 5]
 - OS: [Android 14]
 - Rooted: [No]
 - Version: [3.10]

### PR DESCRIPTION
**Pull request by Rahulraj888**
fixes #4327

Describe the bug
When there is only one item in the Trash Bin, the selected item is cancelled after clicking 'Select All'

To Reproduce

Click on 'Hamburger' menu
Click on 'Trash Bin'
Long press to select an item
Click on 'v' icon
Click on 'Select All'
Expected behavior
The selected item should remain selected after clicking ‘Select All’, even if it is the only item in the Trash Bin

Test Case scenarios's checked:
1. Selected single file and clicked on 'Selected All'. The item is still selected.
2. Selected a few and clicked 'Selected All'. Now, all the items are selected.

Device: Samsung Galaxy S24 (SM-S921W).

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/ui/selection/SelectionPopupMenu.kt [hunk 1]
```diff
@@ -84,11 +84,12 @@ class SelectionPopupMenu(
         when (item?.itemId) {
             R.id.select_all -> {
                 // select_all
-                recyclerAdapter.toggleChecked(
-                    !recyclerAdapter
-                        .areAllChecked(currentPath),
-                    currentPath,
-                )
+                if (!recyclerAdapter.areAllChecked(currentPath)) {
+                    recyclerAdapter.toggleChecked(
```
Comment (Rahulraj888) [inline app/src/main/java/com/amaze/filemanager/ui/selection/SelectionPopupMenu.kt:88]: This function toggleChecked() returns true if everything is already selected. I have added a check, where we won't go further if everthing is already selected.

**Review by EmmanuelMess — APPROVED** [review]

**Review by VishalNehra — APPROVED** [review]
