### PR TITLE
fix: auto reload not working

### LINKED ISSUE #3839: Operations doesn't get reflected correctly in current directory after they're finished (copy / move / delete)
Sometimes after we perform an operation, we see the status as completed, the directory refreshes on itself, however we don't see the result. Manually refreshing or going back to parent directory and back shows the changes correctly.

### PR DESCRIPTION
**Pull request by VishnuSanal**
#### Issue tracker   
Fixes https://github.com/TeamAmaze/AmazeFileManager/issues/3839

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  

- Device: Moto G34
- OS: Android 15 (VanillaIceCream)

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

## changes

- add package names to all intents to trigger `intent_load_list_receiver` (ref: https://stackoverflow.com/a/76920719/9652621).
- scope `intent_load_list_receiver` from `#onStart` to `#onStop` to sync changes across tabs.

### CODE REVIEW

**Comment by rjakubo** [comment]
There are lot of changes and fixes in the release 3.11. Therefore I would like not switch back to release 3.10. Can you provide a hotfix release on IzzyOnDroid that fix the problem from this issue (see also #3839)

**Comment by EmmanuelMess** [comment]
> There are lot of changes and fixes in the release 3.11. Therefore I would like not switch back to release 3.10. Can you provide a hotfix release on IzzyOnDroid that fix the problem from this issue (see also #3839)

We can provide a hotfix if it is fixed in release/4.0. @VishnuSanal is this PR in the works?

**Comment by rjakubo** [comment]
Thanks for your feedback 🙂

File: app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java [hunk 1]
```diff
@@ -402,7 +402,7 @@ void loadViews() {
     }
   }
 
-  private BroadcastReceiver receiver2 =
+  private BroadcastReceiver intent_load_list_receiver =
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java]: Use camel case

**Review by EmmanuelMess — CHANGES_REQUESTED** [review]

**Review by EmmanuelMess — APPROVED** [review]
Tested on emulator for move and delete.

**Comment by rjakubo** [comment]
Hi,
I see that the changes for this issue are merged into release/4.0. Do you have maybe already a date for the hotfix release 3.11.2?
Best regards,
Robert

**Comment by VishnuSanal** [comment]
> Hi, I see that the changes for this issue are merged into release/4.0. Do you have maybe already a date for the hotfix release 3.11.2? Best regards, Robert

soon!! @EmmanuelMess was worrking on some translation fixes, we will release the new version as soon as he is done :) and yeah I also agree that this is a really annoying bug :(

**Comment by PaduaPlay** [comment]
> soon!! @EmmanuelMess was worrking on some translation fixes, we will release the new version as soon as he is done :) and yeah I also agree that this is a really annoying bug :(

Thanks for the quick turnaround on the fix, @VishnuSanal and @EmmanuelMess. 

Any ETA for 3.11.2?
