### PR TITLE
Fix drawer category views not refreshing after file operations

### LINKED ISSUE #4558: Refresh not work when deleting files in "Images", "Videos", etc.
**Describe the bug**
v3.11.2 Refresh not work when deleting files in "Images", "Videos", etc.

**To Reproduce**
1. Go to the drawer
2. click "Images", "Videos", "Audio" (any one of it)
3. delete a file

**Expected behavior**
The file should be deleted and disappear on screen

**Smartphone (please complete the following information):**
 - Device: Google Pixel 9
 - OS: Android 16
 - Rooted: No
 - Version: 3.11.2

**Additional context**

### PR DESCRIPTION
**Pull request by geoffreysisco**
## Description

Drawer category views did not consistently reflect filesystem changes
after file operations such as create and delete.

In some categories (Documents, APKs, Recent Files), queries could include
entries from Amaze's trash directory (.AmazeData), causing deleted files
to remain visible and allowing repeated deletes to create duplicate
Trash Bin entries.

This PR addresses the issue by:
- forcing reload for drawer category views to ensure fresh data after operations
- filtering Amaze trash paths from category queries

This ensures drawer views correctly reflect the current filesystem state
across all categories.

#### Issue tracker
Fixes #4558

#### Automatic tests
- [ ] Added test cases

#### Manual tests
- [x] Done

- Device: Pixel 9 Pro (emulator)
- OS: Android 16.0
- Rooted: No
- Version: 3.11.2

Verified in:
- Documents
- APKs
- Recent Files
- Images
- Videos
- Audio

Scenarios tested:
- Delete file → removed from drawer view
- Repeat delete → not possible (item is no longer visible after deletion)

#### Before

https://github.com/user-attachments/assets/4d083fba-5e38-4df2-9763-057fb53fecad

#### After

https://github.com/user-attachments/assets/9343bcff-60e7-4ba5-8a25-73a66d879b06

#### Build tasks success
Successfully running the following tasks locally:
- [x] `./gradlew assembleDebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java [hunk 1]
```diff
@@ -92,6 +92,7 @@ public class LoadFilesListTask
     extends AsyncTask<Void, Throwable, Pair<OpenMode, List<LayoutElementParcelable>>> {
 
   private static final Logger LOG = LoggerFactory.getLogger(LoadFilesListTask.class);
+  private static final String AMAZE_TRASH_PATH = "/storage/emulated/0/.AmazeData";
```
Comment (VishnuSanal) [inline app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java]: can we pls use `AppConfig.TRASH_BIN_BASE_PATH` here?

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java [hunk 2]
```diff
@@ -437,7 +438,9 @@ else if (cursor.getCount() > 0 && cursor.moveToFirst()) {
     else if (cursor.getCount() > 0 && cursor.moveToFirst()) {
       do {
         String path = cursor.getString(cursor.getColumnIndex(MediaStore.Files.FileColumns.DATA));
-
+        if (path != null && path.startsWith(AMAZE_TRASH_PATH)) {
+          continue;
+        }
```
Comment (VishnuSanal) [inline app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java]: hmm, nice, but I think we can add this selection to the cursor itself like below. WDYT?

```kotlin
    final String[] projection = {MediaStore.Files.FileColumns.DATA};
    final String selection = MediaStore.Files.FileColumns.DATA + " NOT LIKE ?";
    final String[] selectionArgs = new String[] {AppConfig.TRASH_BIN_BASE_PATH + "%"};
    Cursor cursor =
        context
            .getContentResolver()
            .query(MediaStore.Files.getContentUri("external"), projection, selection, selectionArgs, null);
```

**Review by VishnuSanal — CHANGES_REQUESTED** [review]
hi @geoffreysisco great work, thanks for contributing to amaze! :) I have some comments, please address them, and we are good to go, tahnsk!

- also, can you pls add the trash directory check to all quick access menu listings too? thanks!

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java (hunk 1 above)
Comment (geoffreysisco) [reply app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java]: `TRASH_BIN_BASE_PATH` is currently private in AppConfig, so it’s not accessible here.

I can expose it via a getter (e.g. `AppConfig.getTrashBinBasePath()`) and use that instead — let me know if you’d prefer a different approach.

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java (hunk 2 above)
Comment (geoffreysisco) [reply app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java]: I agree, that makes sense. I’ll move the trash exclusion into the query instead of filtering in the loop.

**Comment by geoffreysisco** [comment]
Thanks for the review.

I’ve started addressing the comments.

Documents, APKs, and Recent files now exclude the trash directory at query time instead of filtering in the loop.

For Images/Videos/Audio, the stale delete behavior is already handled via the `forceReload` change in `MainFragment` for `OpenMode.CUSTOM`, but they still go through `listMediaCommon()` for querying.

When you mentioned “all quick access menu listings,” should the trash-path exclusion also be applied in `listMediaCommon()` for Images/Videos/Audio, or only to the MediaStore.Files-based listings touched here (Documents/APKs/Recent files)?

**Comment by geoffreysisco** [comment]
I went ahead and applied the trash-path exclusion across all quick access menu listings.

For Images/Videos/Audio, I extended `listMediaCommon()`  to support `selectionArgs` and added the same exclusion there, so filtering is now handled consistently at query time instead of in the loop.

Let me know if you'd prefer this scoped differently.

**Review by VishnuSanal — APPROVED** [review]
LGTM, thanks! 🚀
